### PR TITLE
Fix #931 Blank producer in playlist does not have audio normalization

### LINKED ISSUE #931: Blank producer in playlist does not have audio normalization
Example command:
melt color:red in=0 out=25 -blank 25 color:blue in=0 out=25 -consumer avformat:test.mp4

The command will fail after processing frame 26 because the audio can not be converted to the requested format.

### PR DESCRIPTION
**Pull request by bmatherly**
* Add new blank producer
* Use the blank producer in the playlist so that blank frames have normalization filters attached.

One side effect of this is that a playlist must be initialized with a profile. Some of the normalization filters depend on it.

### CODE REVIEW

File: src/framework/mlt_playlist.h [hunk 1]
```diff
@@ -71,7 +71,7 @@ typedef struct playlist_entry_s playlist_entry;
 struct mlt_playlist_s
 {
     struct mlt_producer_s parent;
-    struct mlt_producer_s blank;
+    struct mlt_producer_s blank; // Deprecated
```
Comment (ddennedy) [inline src/framework/mlt_playlist.h:74]: This comment should have 3 slashes so it is picked up by doxygen for API docs.

File: src/modules/core/producer_blank.yml [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+identifier: blank
+title: Blank
+version: 1
+copyright: Meltytech, LLC
+license: LGPLv2.1
+language: en
+tags:
+  - Video
+  - Audio
+description: A blank frame generator.
```
Comment (ddennedy) [inline src/modules/core/producer_blank.yml:12]: "blank" is too redundant in this documentation. What is the audio/video user experience of "blank" - black silence? Also, since this line is not a sentence it should not end with a period.

File: src/modules/core/producer_blank.c [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+#include <framework/mlt_producer.h>
+
+#include <stdlib.h>
+
+static int producer_get_frame(mlt_producer self, mlt_frame_ptr frame, int index)
+{
+    // Generate a frame
+    *frame = mlt_frame_init(MLT_PRODUCER_SERVICE(self));
+
+    if (*frame != NULL) {
```
Comment (ddennedy) [inline src/modules/core/producer_blank.c:30]: No need to compare with NULL  - not consistent with the majority of the code.

File: src/modules/core/producer_blank.c [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+    free(producer);
+}
+
+mlt_producer producer_blank_init(mlt_profile profile,
+                                 mlt_service_type type,
+                                 const char *id,
+                                 char *arg)
+{
+    mlt_producer self = calloc(1, sizeof(struct mlt_producer_s));
+    if (self != NULL && mlt_producer_init(self, NULL) == 0) {
```
Comment (ddennedy) [inline src/modules/core/producer_blank.c:58]: No need to compare with NULL and zero.

**Review by ddennedy — CHANGES_REQUESTED** [review]
I think `mlt_playlist_init()` should be deprecated. `Playlist::Playlist()` depends on it, but it could call `mlt_playlist_new(nullptr)` as I am not sure we can remove that constructor.

File: src/modules/core/producer_blank.yml (hunk 2 above)
Comment (bmatherly) [reply src/modules/core/producer_blank.yml:12]: I agree that the word is generic. But I am reusing the word as it is already defined in the framework:
https://github.com/mltframework/mlt/blob/b2787f9069004bb89af8d3d15d7761b024671197/src/framework/mlt_producer.c#L227

Here is a proposal for a more detailed description. Let me know what you think:

> A "Blank" producer returns frames that are transparent and silent. These frames are suitable for creating blank spaces in a playlist. mlt_producer_is_blank() will return 1 on this producer.

Comment (ddennedy) [reply src/modules/core/producer_blank.yml:12]: "transparent" is not accurate because it is only considered transparent when the image format is rgba. Let's just say silent white. Otherwise, I like it's reference to `mlt_producer_is_blank`.

File: src/framework/mlt_playlist.h (hunk 1 above)
Comment (bmatherly) [reply src/framework/mlt_playlist.h]: done

File: src/modules/core/producer_blank.yml (hunk 2 above)
Comment (bmatherly) [reply src/modules/core/producer_blank.yml]: done

File: src/modules/core/producer_blank.c (hunk 3 above)
Comment (bmatherly) [reply src/modules/core/producer_blank.c]: done

File: src/modules/core/producer_blank.c (hunk 4 above)
Comment (bmatherly) [reply src/modules/core/producer_blank.c]: done

**Comment by bmatherly** [comment]
> I think mlt_playlist_init() should be deprecated. Playlist::Playlist() depends on it, but it could call mlt_playlist_new(nullptr) as I am not sure we can remove that constructor.

Done

**Review by ddennedy — APPROVED** [review]
